# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Demo Testing CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Copy to build
        run: |
          ls -al
          git fetch
          echo 'checkout -b build'
          git checkout -b build
          echo 'git pull origin build'
          echo 'git merge master'
          git merge master
          echo 'git push origin build'
          git push origin build
